name: Run autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: select tests to run
        required: true
        type: choise
        default: all
        options:
          - all

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Copy sourse code
        uses: actions/checkout@v4
      - name: Set up Python env
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest -v
      - name: Install Firefox and GeckoDriver
        run:
          sudo apt-get update
          sudo apt-get install -y firefox
          GECKODRIVER_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | grep tag_name | cut -d '"' -f 4)
          wget https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
          tar -xvzf geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/geckodriver
